### ISSUE TITLE
pytorch

### ISSUE THREAD

**Issue by 18222278799** [jind11/Deep-PICO-Detection#1]
i really want to realize them by pytorch, it is easy to check.
Best wishes

**Comment by jind11** [comment]
hi, this is an empty repository. Are you requesting the code to which paper? Thanks!

**Comment by 18222278799** [comment]
i have read your paper " Advancing PICO Element Detection in Medical Text via Deep Neural Networks"  which is received in NIPS, it is very valuable. So i want to learn the code of the paper. Thanks a lot. 

Hope you always have a great day!

**Comment by jind11** [comment]
I have the code in tensorflow for this paper. If you want, I can release it in the next week.

**Comment by 18222278799** [comment]
Oh,thanks very much.

**Comment by 18222278799** [comment]
thankyou
