### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 18: invalid continuation byte

### ISSUE THREAD

**Issue by Hanmii** [jind11/Deep-PICO-Detection#5]
hello, when i load the word embedding , there is an error:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 18: invalid continuation byte

can u help me?

**Comment by jind11** [comment]
Could you let me know which line is causing this error and what is your python version?

**Comment by Hanmii** [comment]
Line 328 in /lstm_model/data_utils.py /, and the python version is 3.6.
Thanks!

**Comment by jind11** [comment]
I  suggest two solutions: 1. I used python 2.7 when writing this code, so could you try changing to python 2.7; 2. You can try changing "r" to "rb" in line 326 and 327. Let me know if you have solved the issue.

**Comment by Hanmii** [comment]
Thanks for your answers and I have solved this issue by changing the python version to 2.7 ! Thanks!!

**Comment by jind11** [comment]
Good to know! Since this issue is solved, I am going to close it.
